// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type AccountRatedMoviesSortBy string

const (
	AccountRatedMoviesSortByCreatedAtAsc  AccountRatedMoviesSortBy = "created_at.asc"
	AccountRatedMoviesSortByCreatedAtDesc AccountRatedMoviesSortBy = "created_at.desc"
)

func (e AccountRatedMoviesSortBy) ToPointer() *AccountRatedMoviesSortBy {
	return &e
}

func (e *AccountRatedMoviesSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at.asc":
		fallthrough
	case "created_at.desc":
		*e = AccountRatedMoviesSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountRatedMoviesSortBy: %v", v)
	}
}

type AccountRatedMoviesRequest struct {
	AccountID int                       `default:"null" pathParam:"style=simple,explode=false,name=account_id"`
	Language  *string                   `default:"en-US" queryParam:"style=form,explode=true,name=language"`
	Page      *int                      `default:"1" queryParam:"style=form,explode=true,name=page"`
	SessionID *string                   `queryParam:"style=form,explode=true,name=session_id"`
	SortBy    *AccountRatedMoviesSortBy `default:"created_at.asc" queryParam:"style=form,explode=true,name=sort_by"`
}

func (a AccountRatedMoviesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountRatedMoviesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountRatedMoviesRequest) GetAccountID() int {
	if o == nil {
		return 0
	}
	return o.AccountID
}

func (o *AccountRatedMoviesRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *AccountRatedMoviesRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AccountRatedMoviesRequest) GetSessionID() *string {
	if o == nil {
		return nil
	}
	return o.SessionID
}

func (o *AccountRatedMoviesRequest) GetSortBy() *AccountRatedMoviesSortBy {
	if o == nil {
		return nil
	}
	return o.SortBy
}

type AccountRatedMovies200ApplicationJSONResults struct {
	Adult            *bool    `default:"true" json:"adult"`
	BackdropPath     *string  `json:"backdrop_path,omitempty"`
	GenreIds         []int64  `json:"genre_ids,omitempty"`
	ID               *int64   `default:"0" json:"id"`
	OriginalLanguage *string  `json:"original_language,omitempty"`
	OriginalTitle    *string  `json:"original_title,omitempty"`
	Overview         *string  `json:"overview,omitempty"`
	Popularity       *float64 `default:"0" json:"popularity"`
	PosterPath       *string  `json:"poster_path,omitempty"`
	Rating           *int64   `default:"0" json:"rating"`
	ReleaseDate      *string  `json:"release_date,omitempty"`
	Title            *string  `json:"title,omitempty"`
	Video            *bool    `default:"true" json:"video"`
	VoteAverage      *float64 `default:"0" json:"vote_average"`
	VoteCount        *int64   `default:"0" json:"vote_count"`
}

func (a AccountRatedMovies200ApplicationJSONResults) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountRatedMovies200ApplicationJSONResults) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetBackdropPath() *string {
	if o == nil {
		return nil
	}
	return o.BackdropPath
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetGenreIds() []int64 {
	if o == nil {
		return nil
	}
	return o.GenreIds
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetOriginalLanguage() *string {
	if o == nil {
		return nil
	}
	return o.OriginalLanguage
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetOriginalTitle() *string {
	if o == nil {
		return nil
	}
	return o.OriginalTitle
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetOverview() *string {
	if o == nil {
		return nil
	}
	return o.Overview
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetPosterPath() *string {
	if o == nil {
		return nil
	}
	return o.PosterPath
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetRating() *int64 {
	if o == nil {
		return nil
	}
	return o.Rating
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetReleaseDate() *string {
	if o == nil {
		return nil
	}
	return o.ReleaseDate
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetVideo() *bool {
	if o == nil {
		return nil
	}
	return o.Video
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetVoteAverage() *float64 {
	if o == nil {
		return nil
	}
	return o.VoteAverage
}

func (o *AccountRatedMovies200ApplicationJSONResults) GetVoteCount() *int64 {
	if o == nil {
		return nil
	}
	return o.VoteCount
}

// AccountRatedMovies200ApplicationJSON - 200
type AccountRatedMovies200ApplicationJSON struct {
	Page         *int64                                        `default:"0" json:"page"`
	Results      []AccountRatedMovies200ApplicationJSONResults `json:"results,omitempty"`
	TotalPages   *int64                                        `default:"0" json:"total_pages"`
	TotalResults *int64                                        `default:"0" json:"total_results"`
}

func (a AccountRatedMovies200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountRatedMovies200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountRatedMovies200ApplicationJSON) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AccountRatedMovies200ApplicationJSON) GetResults() []AccountRatedMovies200ApplicationJSONResults {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *AccountRatedMovies200ApplicationJSON) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

func (o *AccountRatedMovies200ApplicationJSON) GetTotalResults() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalResults
}

type AccountRatedMoviesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	AccountRatedMovies200ApplicationJSONObject *AccountRatedMovies200ApplicationJSON
}

func (o *AccountRatedMoviesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AccountRatedMoviesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AccountRatedMoviesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AccountRatedMoviesResponse) GetAccountRatedMovies200ApplicationJSONObject() *AccountRatedMovies200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AccountRatedMovies200ApplicationJSONObject
}
