// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type AccountWatchlistTvSortBy string

const (
	AccountWatchlistTvSortByCreatedAtAsc  AccountWatchlistTvSortBy = "created_at.asc"
	AccountWatchlistTvSortByCreatedAtDesc AccountWatchlistTvSortBy = "created_at.desc"
)

func (e AccountWatchlistTvSortBy) ToPointer() *AccountWatchlistTvSortBy {
	return &e
}

func (e *AccountWatchlistTvSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at.asc":
		fallthrough
	case "created_at.desc":
		*e = AccountWatchlistTvSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountWatchlistTvSortBy: %v", v)
	}
}

type AccountWatchlistTvRequest struct {
	AccountID int                       `default:"null" pathParam:"style=simple,explode=false,name=account_id"`
	Language  *string                   `default:"en-US" queryParam:"style=form,explode=true,name=language"`
	Page      *int                      `default:"1" queryParam:"style=form,explode=true,name=page"`
	SessionID *string                   `queryParam:"style=form,explode=true,name=session_id"`
	SortBy    *AccountWatchlistTvSortBy `default:"created_at.asc" queryParam:"style=form,explode=true,name=sort_by"`
}

func (a AccountWatchlistTvRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountWatchlistTvRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountWatchlistTvRequest) GetAccountID() int {
	if o == nil {
		return 0
	}
	return o.AccountID
}

func (o *AccountWatchlistTvRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *AccountWatchlistTvRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AccountWatchlistTvRequest) GetSessionID() *string {
	if o == nil {
		return nil
	}
	return o.SessionID
}

func (o *AccountWatchlistTvRequest) GetSortBy() *AccountWatchlistTvSortBy {
	if o == nil {
		return nil
	}
	return o.SortBy
}

type AccountWatchlistTv200ApplicationJSONResults struct {
	Adult            *bool    `default:"true" json:"adult"`
	BackdropPath     *string  `json:"backdrop_path,omitempty"`
	FirstAirDate     *string  `json:"first_air_date,omitempty"`
	GenreIds         []int64  `json:"genre_ids,omitempty"`
	ID               *int64   `default:"0" json:"id"`
	Name             *string  `json:"name,omitempty"`
	OriginCountry    []string `json:"origin_country,omitempty"`
	OriginalLanguage *string  `json:"original_language,omitempty"`
	OriginalName     *string  `json:"original_name,omitempty"`
	Overview         *string  `json:"overview,omitempty"`
	Popularity       *float64 `default:"0" json:"popularity"`
	PosterPath       *string  `json:"poster_path,omitempty"`
	VoteAverage      *float64 `default:"0" json:"vote_average"`
	VoteCount        *int64   `default:"0" json:"vote_count"`
}

func (a AccountWatchlistTv200ApplicationJSONResults) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountWatchlistTv200ApplicationJSONResults) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetBackdropPath() *string {
	if o == nil {
		return nil
	}
	return o.BackdropPath
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetFirstAirDate() *string {
	if o == nil {
		return nil
	}
	return o.FirstAirDate
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetGenreIds() []int64 {
	if o == nil {
		return nil
	}
	return o.GenreIds
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetOriginCountry() []string {
	if o == nil {
		return nil
	}
	return o.OriginCountry
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetOriginalLanguage() *string {
	if o == nil {
		return nil
	}
	return o.OriginalLanguage
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetOverview() *string {
	if o == nil {
		return nil
	}
	return o.Overview
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetPosterPath() *string {
	if o == nil {
		return nil
	}
	return o.PosterPath
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetVoteAverage() *float64 {
	if o == nil {
		return nil
	}
	return o.VoteAverage
}

func (o *AccountWatchlistTv200ApplicationJSONResults) GetVoteCount() *int64 {
	if o == nil {
		return nil
	}
	return o.VoteCount
}

// AccountWatchlistTv200ApplicationJSON - 200
type AccountWatchlistTv200ApplicationJSON struct {
	Page         *int64                                        `default:"0" json:"page"`
	Results      []AccountWatchlistTv200ApplicationJSONResults `json:"results,omitempty"`
	TotalPages   *int64                                        `default:"0" json:"total_pages"`
	TotalResults *int64                                        `default:"0" json:"total_results"`
}

func (a AccountWatchlistTv200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountWatchlistTv200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountWatchlistTv200ApplicationJSON) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AccountWatchlistTv200ApplicationJSON) GetResults() []AccountWatchlistTv200ApplicationJSONResults {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *AccountWatchlistTv200ApplicationJSON) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

func (o *AccountWatchlistTv200ApplicationJSON) GetTotalResults() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalResults
}

type AccountWatchlistTvResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	AccountWatchlistTv200ApplicationJSONObject *AccountWatchlistTv200ApplicationJSON
}

func (o *AccountWatchlistTvResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AccountWatchlistTvResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AccountWatchlistTvResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AccountWatchlistTvResponse) GetAccountWatchlistTv200ApplicationJSONObject() *AccountWatchlistTv200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AccountWatchlistTv200ApplicationJSONObject
}
