// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type AccountRatedTvEpisodesSortBy string

const (
	AccountRatedTvEpisodesSortByCreatedAtAsc  AccountRatedTvEpisodesSortBy = "created_at.asc"
	AccountRatedTvEpisodesSortByCreatedAtDesc AccountRatedTvEpisodesSortBy = "created_at.desc"
)

func (e AccountRatedTvEpisodesSortBy) ToPointer() *AccountRatedTvEpisodesSortBy {
	return &e
}

func (e *AccountRatedTvEpisodesSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at.asc":
		fallthrough
	case "created_at.desc":
		*e = AccountRatedTvEpisodesSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountRatedTvEpisodesSortBy: %v", v)
	}
}

type AccountRatedTvEpisodesRequest struct {
	AccountID int                           `default:"null" pathParam:"style=simple,explode=false,name=account_id"`
	Language  *string                       `default:"en-US" queryParam:"style=form,explode=true,name=language"`
	Page      *int                          `default:"1" queryParam:"style=form,explode=true,name=page"`
	SessionID *string                       `queryParam:"style=form,explode=true,name=session_id"`
	SortBy    *AccountRatedTvEpisodesSortBy `default:"created_at.asc" queryParam:"style=form,explode=true,name=sort_by"`
}

func (a AccountRatedTvEpisodesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountRatedTvEpisodesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountRatedTvEpisodesRequest) GetAccountID() int {
	if o == nil {
		return 0
	}
	return o.AccountID
}

func (o *AccountRatedTvEpisodesRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *AccountRatedTvEpisodesRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AccountRatedTvEpisodesRequest) GetSessionID() *string {
	if o == nil {
		return nil
	}
	return o.SessionID
}

func (o *AccountRatedTvEpisodesRequest) GetSortBy() *AccountRatedTvEpisodesSortBy {
	if o == nil {
		return nil
	}
	return o.SortBy
}

type AccountRatedTvEpisodes200ApplicationJSONResults struct {
	AirDate        *string  `json:"air_date,omitempty"`
	EpisodeNumber  *int64   `default:"0" json:"episode_number"`
	ID             *int64   `default:"0" json:"id"`
	Name           *string  `json:"name,omitempty"`
	Overview       *string  `json:"overview,omitempty"`
	ProductionCode *string  `json:"production_code,omitempty"`
	Rating         *int64   `default:"0" json:"rating"`
	Runtime        *int64   `default:"0" json:"runtime"`
	SeasonNumber   *int64   `default:"0" json:"season_number"`
	ShowID         *int64   `default:"0" json:"show_id"`
	StillPath      *string  `json:"still_path,omitempty"`
	VoteAverage    *float64 `default:"0" json:"vote_average"`
	VoteCount      *int64   `default:"0" json:"vote_count"`
}

func (a AccountRatedTvEpisodes200ApplicationJSONResults) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountRatedTvEpisodes200ApplicationJSONResults) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetAirDate() *string {
	if o == nil {
		return nil
	}
	return o.AirDate
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetEpisodeNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.EpisodeNumber
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetOverview() *string {
	if o == nil {
		return nil
	}
	return o.Overview
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetProductionCode() *string {
	if o == nil {
		return nil
	}
	return o.ProductionCode
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetRating() *int64 {
	if o == nil {
		return nil
	}
	return o.Rating
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetRuntime() *int64 {
	if o == nil {
		return nil
	}
	return o.Runtime
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetSeasonNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.SeasonNumber
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetShowID() *int64 {
	if o == nil {
		return nil
	}
	return o.ShowID
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetStillPath() *string {
	if o == nil {
		return nil
	}
	return o.StillPath
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetVoteAverage() *float64 {
	if o == nil {
		return nil
	}
	return o.VoteAverage
}

func (o *AccountRatedTvEpisodes200ApplicationJSONResults) GetVoteCount() *int64 {
	if o == nil {
		return nil
	}
	return o.VoteCount
}

// AccountRatedTvEpisodes200ApplicationJSON - 200
type AccountRatedTvEpisodes200ApplicationJSON struct {
	Page         *int64                                            `default:"0" json:"page"`
	Results      []AccountRatedTvEpisodes200ApplicationJSONResults `json:"results,omitempty"`
	TotalPages   *int64                                            `default:"0" json:"total_pages"`
	TotalResults *int64                                            `default:"0" json:"total_results"`
}

func (a AccountRatedTvEpisodes200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountRatedTvEpisodes200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountRatedTvEpisodes200ApplicationJSON) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AccountRatedTvEpisodes200ApplicationJSON) GetResults() []AccountRatedTvEpisodes200ApplicationJSONResults {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *AccountRatedTvEpisodes200ApplicationJSON) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

func (o *AccountRatedTvEpisodes200ApplicationJSON) GetTotalResults() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalResults
}

type AccountRatedTvEpisodesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	AccountRatedTvEpisodes200ApplicationJSONObject *AccountRatedTvEpisodes200ApplicationJSON
}

func (o *AccountRatedTvEpisodesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AccountRatedTvEpisodesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AccountRatedTvEpisodesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AccountRatedTvEpisodesResponse) GetAccountRatedTvEpisodes200ApplicationJSONObject() *AccountRatedTvEpisodes200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AccountRatedTvEpisodes200ApplicationJSONObject
}
