// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type AccountFavoriteTvSortBy string

const (
	AccountFavoriteTvSortByCreatedAtAsc  AccountFavoriteTvSortBy = "created_at.asc"
	AccountFavoriteTvSortByCreatedAtDesc AccountFavoriteTvSortBy = "created_at.desc"
)

func (e AccountFavoriteTvSortBy) ToPointer() *AccountFavoriteTvSortBy {
	return &e
}

func (e *AccountFavoriteTvSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at.asc":
		fallthrough
	case "created_at.desc":
		*e = AccountFavoriteTvSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountFavoriteTvSortBy: %v", v)
	}
}

type AccountFavoriteTvRequest struct {
	AccountID int                      `default:"null" pathParam:"style=simple,explode=false,name=account_id"`
	Language  *string                  `default:"en-US" queryParam:"style=form,explode=true,name=language"`
	Page      *int                     `default:"1" queryParam:"style=form,explode=true,name=page"`
	SessionID *string                  `queryParam:"style=form,explode=true,name=session_id"`
	SortBy    *AccountFavoriteTvSortBy `default:"created_at.asc" queryParam:"style=form,explode=true,name=sort_by"`
}

func (a AccountFavoriteTvRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountFavoriteTvRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountFavoriteTvRequest) GetAccountID() int {
	if o == nil {
		return 0
	}
	return o.AccountID
}

func (o *AccountFavoriteTvRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *AccountFavoriteTvRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AccountFavoriteTvRequest) GetSessionID() *string {
	if o == nil {
		return nil
	}
	return o.SessionID
}

func (o *AccountFavoriteTvRequest) GetSortBy() *AccountFavoriteTvSortBy {
	if o == nil {
		return nil
	}
	return o.SortBy
}

type AccountFavoriteTv200ApplicationJSONResults struct {
	Adult            *bool    `default:"true" json:"adult"`
	BackdropPath     *string  `json:"backdrop_path,omitempty"`
	FirstAirDate     *string  `json:"first_air_date,omitempty"`
	GenreIds         []int64  `json:"genre_ids,omitempty"`
	ID               *int64   `default:"0" json:"id"`
	Name             *string  `json:"name,omitempty"`
	OriginCountry    []string `json:"origin_country,omitempty"`
	OriginalLanguage *string  `json:"original_language,omitempty"`
	OriginalName     *string  `json:"original_name,omitempty"`
	Overview         *string  `json:"overview,omitempty"`
	Popularity       *float64 `default:"0" json:"popularity"`
	PosterPath       *string  `json:"poster_path,omitempty"`
	VoteAverage      *float64 `default:"0" json:"vote_average"`
	VoteCount        *int64   `default:"0" json:"vote_count"`
}

func (a AccountFavoriteTv200ApplicationJSONResults) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountFavoriteTv200ApplicationJSONResults) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetBackdropPath() *string {
	if o == nil {
		return nil
	}
	return o.BackdropPath
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetFirstAirDate() *string {
	if o == nil {
		return nil
	}
	return o.FirstAirDate
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetGenreIds() []int64 {
	if o == nil {
		return nil
	}
	return o.GenreIds
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetOriginCountry() []string {
	if o == nil {
		return nil
	}
	return o.OriginCountry
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetOriginalLanguage() *string {
	if o == nil {
		return nil
	}
	return o.OriginalLanguage
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetOverview() *string {
	if o == nil {
		return nil
	}
	return o.Overview
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetPosterPath() *string {
	if o == nil {
		return nil
	}
	return o.PosterPath
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetVoteAverage() *float64 {
	if o == nil {
		return nil
	}
	return o.VoteAverage
}

func (o *AccountFavoriteTv200ApplicationJSONResults) GetVoteCount() *int64 {
	if o == nil {
		return nil
	}
	return o.VoteCount
}

// AccountFavoriteTv200ApplicationJSON - 200
type AccountFavoriteTv200ApplicationJSON struct {
	Page         *int64                                       `default:"0" json:"page"`
	Results      []AccountFavoriteTv200ApplicationJSONResults `json:"results,omitempty"`
	TotalPages   *int64                                       `default:"0" json:"total_pages"`
	TotalResults *int64                                       `default:"0" json:"total_results"`
}

func (a AccountFavoriteTv200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountFavoriteTv200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountFavoriteTv200ApplicationJSON) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AccountFavoriteTv200ApplicationJSON) GetResults() []AccountFavoriteTv200ApplicationJSONResults {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *AccountFavoriteTv200ApplicationJSON) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

func (o *AccountFavoriteTv200ApplicationJSON) GetTotalResults() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalResults
}

type AccountFavoriteTvResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	AccountFavoriteTv200ApplicationJSONObject *AccountFavoriteTv200ApplicationJSON
}

func (o *AccountFavoriteTvResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AccountFavoriteTvResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AccountFavoriteTvResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AccountFavoriteTvResponse) GetAccountFavoriteTv200ApplicationJSONObject() *AccountFavoriteTv200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AccountFavoriteTv200ApplicationJSONObject
}
