// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type AuthenticationDeleteSessionRequestBody struct {
	RawBody string `json:"RAW_BODY"`
}

func (o *AuthenticationDeleteSessionRequestBody) GetRawBody() string {
	if o == nil {
		return ""
	}
	return o.RawBody
}

// AuthenticationDeleteSession200ApplicationJSON - 200
type AuthenticationDeleteSession200ApplicationJSON struct {
	Success *bool `default:"true" json:"success"`
}

func (a AuthenticationDeleteSession200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthenticationDeleteSession200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AuthenticationDeleteSession200ApplicationJSON) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

type AuthenticationDeleteSessionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	AuthenticationDeleteSession200ApplicationJSONObject *AuthenticationDeleteSession200ApplicationJSON
}

func (o *AuthenticationDeleteSessionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AuthenticationDeleteSessionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AuthenticationDeleteSessionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AuthenticationDeleteSessionResponse) GetAuthenticationDeleteSession200ApplicationJSONObject() *AuthenticationDeleteSession200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AuthenticationDeleteSession200ApplicationJSONObject
}
