// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/types"
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type ChangesTvListRequest struct {
	EndDate   *types.Date `queryParam:"style=form,explode=true,name=end_date"`
	Page      *int        `default:"1" queryParam:"style=form,explode=true,name=page"`
	StartDate *types.Date `queryParam:"style=form,explode=true,name=start_date"`
}

func (c ChangesTvListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChangesTvListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ChangesTvListRequest) GetEndDate() *types.Date {
	if o == nil {
		return nil
	}
	return o.EndDate
}

func (o *ChangesTvListRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ChangesTvListRequest) GetStartDate() *types.Date {
	if o == nil {
		return nil
	}
	return o.StartDate
}

type ChangesTvList200ApplicationJSONResults struct {
	Adult *bool  `default:"true" json:"adult"`
	ID    *int64 `default:"0" json:"id"`
}

func (c ChangesTvList200ApplicationJSONResults) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChangesTvList200ApplicationJSONResults) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ChangesTvList200ApplicationJSONResults) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *ChangesTvList200ApplicationJSONResults) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

// ChangesTvList200ApplicationJSON - 200
type ChangesTvList200ApplicationJSON struct {
	Page         *int64                                   `default:"0" json:"page"`
	Results      []ChangesTvList200ApplicationJSONResults `json:"results,omitempty"`
	TotalPages   *int64                                   `default:"0" json:"total_pages"`
	TotalResults *int64                                   `default:"0" json:"total_results"`
}

func (c ChangesTvList200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChangesTvList200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ChangesTvList200ApplicationJSON) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ChangesTvList200ApplicationJSON) GetResults() []ChangesTvList200ApplicationJSONResults {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *ChangesTvList200ApplicationJSON) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

func (o *ChangesTvList200ApplicationJSON) GetTotalResults() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalResults
}

type ChangesTvListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	ChangesTvList200ApplicationJSONObject *ChangesTvList200ApplicationJSON
}

func (o *ChangesTvListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ChangesTvListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ChangesTvListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ChangesTvListResponse) GetChangesTvList200ApplicationJSONObject() *ChangesTvList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ChangesTvList200ApplicationJSONObject
}
