// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ConfigurationLanguages200ApplicationJSON struct {
	EnglishName *string `json:"english_name,omitempty"`
	Iso6391     *string `json:"iso_639_1,omitempty"`
	Name        *string `json:"name,omitempty"`
}

func (o *ConfigurationLanguages200ApplicationJSON) GetEnglishName() *string {
	if o == nil {
		return nil
	}
	return o.EnglishName
}

func (o *ConfigurationLanguages200ApplicationJSON) GetIso6391() *string {
	if o == nil {
		return nil
	}
	return o.Iso6391
}

func (o *ConfigurationLanguages200ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type ConfigurationLanguagesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	ConfigurationLanguages200ApplicationJSONObjects []ConfigurationLanguages200ApplicationJSON
}

func (o *ConfigurationLanguagesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ConfigurationLanguagesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ConfigurationLanguagesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ConfigurationLanguagesResponse) GetConfigurationLanguages200ApplicationJSONObjects() []ConfigurationLanguages200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ConfigurationLanguages200ApplicationJSONObjects
}
