// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type DetailsCopyRequest struct {
	NetworkID int `pathParam:"style=simple,explode=false,name=network_id"`
}

func (o *DetailsCopyRequest) GetNetworkID() int {
	if o == nil {
		return 0
	}
	return o.NetworkID
}

type DetailsCopy200ApplicationJSONResults struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

func (o *DetailsCopy200ApplicationJSONResults) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *DetailsCopy200ApplicationJSONResults) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

// DetailsCopy200ApplicationJSON - 200
type DetailsCopy200ApplicationJSON struct {
	ID      *int64                                 `default:"0" json:"id"`
	Results []DetailsCopy200ApplicationJSONResults `json:"results,omitempty"`
}

func (d DetailsCopy200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DetailsCopy200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DetailsCopy200ApplicationJSON) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *DetailsCopy200ApplicationJSON) GetResults() []DetailsCopy200ApplicationJSONResults {
	if o == nil {
		return nil
	}
	return o.Results
}

type DetailsCopyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	DetailsCopy200ApplicationJSONObject *DetailsCopy200ApplicationJSON
}

func (o *DetailsCopyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DetailsCopyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DetailsCopyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DetailsCopyResponse) GetDetailsCopy200ApplicationJSONObject() *DetailsCopy200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.DetailsCopy200ApplicationJSONObject
}
