// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type GenreTvListRequest struct {
	Language *string `default:"en" queryParam:"style=form,explode=true,name=language"`
}

func (g GenreTvListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GenreTvListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GenreTvListRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

type GenreTvList200ApplicationJSONGenres struct {
	ID   *int64  `default:"0" json:"id"`
	Name *string `json:"name,omitempty"`
}

func (g GenreTvList200ApplicationJSONGenres) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GenreTvList200ApplicationJSONGenres) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GenreTvList200ApplicationJSONGenres) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *GenreTvList200ApplicationJSONGenres) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// GenreTvList200ApplicationJSON - 200
type GenreTvList200ApplicationJSON struct {
	Genres []GenreTvList200ApplicationJSONGenres `json:"genres,omitempty"`
}

func (o *GenreTvList200ApplicationJSON) GetGenres() []GenreTvList200ApplicationJSONGenres {
	if o == nil {
		return nil
	}
	return o.Genres
}

type GenreTvListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	GenreTvList200ApplicationJSONObject *GenreTvList200ApplicationJSON
}

func (o *GenreTvListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenreTvListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenreTvListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GenreTvListResponse) GetGenreTvList200ApplicationJSONObject() *GenreTvList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GenreTvList200ApplicationJSONObject
}
