// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type ListRemoveMovieRequestBody struct {
	RawBody string `json:"RAW_BODY"`
}

func (o *ListRemoveMovieRequestBody) GetRawBody() string {
	if o == nil {
		return ""
	}
	return o.RawBody
}

type ListRemoveMovieRequest struct {
	ListID      int                         `pathParam:"style=simple,explode=false,name=list_id"`
	SessionID   string                      `queryParam:"style=form,explode=true,name=session_id"`
	RequestBody *ListRemoveMovieRequestBody `request:"mediaType=application/json"`
}

func (o *ListRemoveMovieRequest) GetListID() int {
	if o == nil {
		return 0
	}
	return o.ListID
}

func (o *ListRemoveMovieRequest) GetSessionID() string {
	if o == nil {
		return ""
	}
	return o.SessionID
}

func (o *ListRemoveMovieRequest) GetRequestBody() *ListRemoveMovieRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

// ListRemoveMovie200ApplicationJSON - 200
type ListRemoveMovie200ApplicationJSON struct {
	StatusCode    *int64  `default:"0" json:"status_code"`
	StatusMessage *string `json:"status_message,omitempty"`
}

func (l ListRemoveMovie200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListRemoveMovie200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListRemoveMovie200ApplicationJSON) GetStatusCode() *int64 {
	if o == nil {
		return nil
	}
	return o.StatusCode
}

func (o *ListRemoveMovie200ApplicationJSON) GetStatusMessage() *string {
	if o == nil {
		return nil
	}
	return o.StatusMessage
}

type ListRemoveMovieResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	ListRemoveMovie200ApplicationJSONObject *ListRemoveMovie200ApplicationJSON
}

func (o *ListRemoveMovieResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListRemoveMovieResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListRemoveMovieResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListRemoveMovieResponse) GetListRemoveMovie200ApplicationJSONObject() *ListRemoveMovie200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ListRemoveMovie200ApplicationJSONObject
}
