// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type ListDeleteRequest struct {
	ListID    int    `pathParam:"style=simple,explode=false,name=list_id"`
	SessionID string `queryParam:"style=form,explode=true,name=session_id"`
}

func (o *ListDeleteRequest) GetListID() int {
	if o == nil {
		return 0
	}
	return o.ListID
}

func (o *ListDeleteRequest) GetSessionID() string {
	if o == nil {
		return ""
	}
	return o.SessionID
}

// ListDelete200ApplicationJSON - 200
type ListDelete200ApplicationJSON struct {
	StatusCode    *int64  `default:"0" json:"status_code"`
	StatusMessage *string `json:"status_message,omitempty"`
}

func (l ListDelete200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDelete200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListDelete200ApplicationJSON) GetStatusCode() *int64 {
	if o == nil {
		return nil
	}
	return o.StatusCode
}

func (o *ListDelete200ApplicationJSON) GetStatusMessage() *string {
	if o == nil {
		return nil
	}
	return o.StatusMessage
}

type ListDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	ListDelete200ApplicationJSONObject *ListDelete200ApplicationJSON
}

func (o *ListDeleteResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListDeleteResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListDeleteResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListDeleteResponse) GetListDelete200ApplicationJSONObject() *ListDelete200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ListDelete200ApplicationJSONObject
}
