// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type MovieCreditsRequest struct {
	MovieID  int     `pathParam:"style=simple,explode=false,name=movie_id"`
	Language *string `default:"en-US" queryParam:"style=form,explode=true,name=language"`
}

func (m MovieCreditsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MovieCreditsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MovieCreditsRequest) GetMovieID() int {
	if o == nil {
		return 0
	}
	return o.MovieID
}

func (o *MovieCreditsRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

type MovieCredits200ApplicationJSONCast struct {
	Adult              *bool    `default:"true" json:"adult"`
	CastID             *int64   `default:"0" json:"cast_id"`
	Character          *string  `json:"character,omitempty"`
	CreditID           *string  `json:"credit_id,omitempty"`
	Gender             *int64   `default:"0" json:"gender"`
	ID                 *int64   `default:"0" json:"id"`
	KnownForDepartment *string  `json:"known_for_department,omitempty"`
	Name               *string  `json:"name,omitempty"`
	Order              *int64   `default:"0" json:"order"`
	OriginalName       *string  `json:"original_name,omitempty"`
	Popularity         *float64 `default:"0" json:"popularity"`
	ProfilePath        *string  `json:"profile_path,omitempty"`
}

func (m MovieCredits200ApplicationJSONCast) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MovieCredits200ApplicationJSONCast) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MovieCredits200ApplicationJSONCast) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *MovieCredits200ApplicationJSONCast) GetCastID() *int64 {
	if o == nil {
		return nil
	}
	return o.CastID
}

func (o *MovieCredits200ApplicationJSONCast) GetCharacter() *string {
	if o == nil {
		return nil
	}
	return o.Character
}

func (o *MovieCredits200ApplicationJSONCast) GetCreditID() *string {
	if o == nil {
		return nil
	}
	return o.CreditID
}

func (o *MovieCredits200ApplicationJSONCast) GetGender() *int64 {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *MovieCredits200ApplicationJSONCast) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *MovieCredits200ApplicationJSONCast) GetKnownForDepartment() *string {
	if o == nil {
		return nil
	}
	return o.KnownForDepartment
}

func (o *MovieCredits200ApplicationJSONCast) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *MovieCredits200ApplicationJSONCast) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *MovieCredits200ApplicationJSONCast) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *MovieCredits200ApplicationJSONCast) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *MovieCredits200ApplicationJSONCast) GetProfilePath() *string {
	if o == nil {
		return nil
	}
	return o.ProfilePath
}

type MovieCredits200ApplicationJSONCrew struct {
	Adult              *bool    `default:"true" json:"adult"`
	CreditID           *string  `json:"credit_id,omitempty"`
	Department         *string  `json:"department,omitempty"`
	Gender             *int64   `default:"0" json:"gender"`
	ID                 *int64   `default:"0" json:"id"`
	Job                *string  `json:"job,omitempty"`
	KnownForDepartment *string  `json:"known_for_department,omitempty"`
	Name               *string  `json:"name,omitempty"`
	OriginalName       *string  `json:"original_name,omitempty"`
	Popularity         *float64 `default:"0" json:"popularity"`
	ProfilePath        *string  `json:"profile_path,omitempty"`
}

func (m MovieCredits200ApplicationJSONCrew) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MovieCredits200ApplicationJSONCrew) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MovieCredits200ApplicationJSONCrew) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *MovieCredits200ApplicationJSONCrew) GetCreditID() *string {
	if o == nil {
		return nil
	}
	return o.CreditID
}

func (o *MovieCredits200ApplicationJSONCrew) GetDepartment() *string {
	if o == nil {
		return nil
	}
	return o.Department
}

func (o *MovieCredits200ApplicationJSONCrew) GetGender() *int64 {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *MovieCredits200ApplicationJSONCrew) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *MovieCredits200ApplicationJSONCrew) GetJob() *string {
	if o == nil {
		return nil
	}
	return o.Job
}

func (o *MovieCredits200ApplicationJSONCrew) GetKnownForDepartment() *string {
	if o == nil {
		return nil
	}
	return o.KnownForDepartment
}

func (o *MovieCredits200ApplicationJSONCrew) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *MovieCredits200ApplicationJSONCrew) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *MovieCredits200ApplicationJSONCrew) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *MovieCredits200ApplicationJSONCrew) GetProfilePath() *string {
	if o == nil {
		return nil
	}
	return o.ProfilePath
}

// MovieCredits200ApplicationJSON - 200
type MovieCredits200ApplicationJSON struct {
	Cast []MovieCredits200ApplicationJSONCast `json:"cast,omitempty"`
	Crew []MovieCredits200ApplicationJSONCrew `json:"crew,omitempty"`
	ID   *int64                               `default:"0" json:"id"`
}

func (m MovieCredits200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MovieCredits200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MovieCredits200ApplicationJSON) GetCast() []MovieCredits200ApplicationJSONCast {
	if o == nil {
		return nil
	}
	return o.Cast
}

func (o *MovieCredits200ApplicationJSON) GetCrew() []MovieCredits200ApplicationJSONCrew {
	if o == nil {
		return nil
	}
	return o.Crew
}

func (o *MovieCredits200ApplicationJSON) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

type MovieCreditsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	MovieCredits200ApplicationJSONObject *MovieCredits200ApplicationJSON
}

func (o *MovieCreditsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MovieCreditsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MovieCreditsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MovieCreditsResponse) GetMovieCredits200ApplicationJSONObject() *MovieCredits200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.MovieCredits200ApplicationJSONObject
}
