// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type MovieRecommendationsRequest struct {
	MovieID  int     `pathParam:"style=simple,explode=false,name=movie_id"`
	Language *string `default:"en-US" queryParam:"style=form,explode=true,name=language"`
	Page     *int    `default:"1" queryParam:"style=form,explode=true,name=page"`
}

func (m MovieRecommendationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MovieRecommendationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MovieRecommendationsRequest) GetMovieID() int {
	if o == nil {
		return 0
	}
	return o.MovieID
}

func (o *MovieRecommendationsRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *MovieRecommendationsRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

// MovieRecommendations200ApplicationJSON - 200
type MovieRecommendations200ApplicationJSON struct {
}

type MovieRecommendationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	MovieRecommendations200ApplicationJSONObject *MovieRecommendations200ApplicationJSON
}

func (o *MovieRecommendationsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MovieRecommendationsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MovieRecommendationsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MovieRecommendationsResponse) GetMovieRecommendations200ApplicationJSONObject() *MovieRecommendations200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.MovieRecommendations200ApplicationJSONObject
}
