// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type MovieNowPlayingListRequest struct {
	Language *string `default:"en-US" queryParam:"style=form,explode=true,name=language"`
	Page     *int    `default:"1" queryParam:"style=form,explode=true,name=page"`
	// ISO-3166-1 code
	Region *string `queryParam:"style=form,explode=true,name=region"`
}

func (m MovieNowPlayingListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MovieNowPlayingListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MovieNowPlayingListRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *MovieNowPlayingListRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *MovieNowPlayingListRequest) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

type MovieNowPlayingList200ApplicationJSONDates struct {
	Maximum *string `json:"maximum,omitempty"`
	Minimum *string `json:"minimum,omitempty"`
}

func (o *MovieNowPlayingList200ApplicationJSONDates) GetMaximum() *string {
	if o == nil {
		return nil
	}
	return o.Maximum
}

func (o *MovieNowPlayingList200ApplicationJSONDates) GetMinimum() *string {
	if o == nil {
		return nil
	}
	return o.Minimum
}

type MovieNowPlayingList200ApplicationJSONResults struct {
	Adult            *bool    `default:"true" json:"adult"`
	BackdropPath     *string  `json:"backdrop_path,omitempty"`
	GenreIds         []int64  `json:"genre_ids,omitempty"`
	ID               *int64   `default:"0" json:"id"`
	OriginalLanguage *string  `json:"original_language,omitempty"`
	OriginalTitle    *string  `json:"original_title,omitempty"`
	Overview         *string  `json:"overview,omitempty"`
	Popularity       *float64 `default:"0" json:"popularity"`
	PosterPath       *string  `json:"poster_path,omitempty"`
	ReleaseDate      *string  `json:"release_date,omitempty"`
	Title            *string  `json:"title,omitempty"`
	Video            *bool    `default:"true" json:"video"`
	VoteAverage      *float64 `default:"0" json:"vote_average"`
	VoteCount        *int64   `default:"0" json:"vote_count"`
}

func (m MovieNowPlayingList200ApplicationJSONResults) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MovieNowPlayingList200ApplicationJSONResults) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetBackdropPath() *string {
	if o == nil {
		return nil
	}
	return o.BackdropPath
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetGenreIds() []int64 {
	if o == nil {
		return nil
	}
	return o.GenreIds
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetOriginalLanguage() *string {
	if o == nil {
		return nil
	}
	return o.OriginalLanguage
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetOriginalTitle() *string {
	if o == nil {
		return nil
	}
	return o.OriginalTitle
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetOverview() *string {
	if o == nil {
		return nil
	}
	return o.Overview
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetPosterPath() *string {
	if o == nil {
		return nil
	}
	return o.PosterPath
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetReleaseDate() *string {
	if o == nil {
		return nil
	}
	return o.ReleaseDate
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetVideo() *bool {
	if o == nil {
		return nil
	}
	return o.Video
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetVoteAverage() *float64 {
	if o == nil {
		return nil
	}
	return o.VoteAverage
}

func (o *MovieNowPlayingList200ApplicationJSONResults) GetVoteCount() *int64 {
	if o == nil {
		return nil
	}
	return o.VoteCount
}

// MovieNowPlayingList200ApplicationJSON - 200
type MovieNowPlayingList200ApplicationJSON struct {
	Dates        *MovieNowPlayingList200ApplicationJSONDates    `json:"dates,omitempty"`
	Page         *int64                                         `default:"0" json:"page"`
	Results      []MovieNowPlayingList200ApplicationJSONResults `json:"results,omitempty"`
	TotalPages   *int64                                         `default:"0" json:"total_pages"`
	TotalResults *int64                                         `default:"0" json:"total_results"`
}

func (m MovieNowPlayingList200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MovieNowPlayingList200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MovieNowPlayingList200ApplicationJSON) GetDates() *MovieNowPlayingList200ApplicationJSONDates {
	if o == nil {
		return nil
	}
	return o.Dates
}

func (o *MovieNowPlayingList200ApplicationJSON) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *MovieNowPlayingList200ApplicationJSON) GetResults() []MovieNowPlayingList200ApplicationJSONResults {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *MovieNowPlayingList200ApplicationJSON) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

func (o *MovieNowPlayingList200ApplicationJSON) GetTotalResults() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalResults
}

type MovieNowPlayingListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	MovieNowPlayingList200ApplicationJSONObject *MovieNowPlayingList200ApplicationJSON
}

func (o *MovieNowPlayingListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MovieNowPlayingListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MovieNowPlayingListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MovieNowPlayingListResponse) GetMovieNowPlayingList200ApplicationJSONObject() *MovieNowPlayingList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.MovieNowPlayingList200ApplicationJSONObject
}
