// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type MovieListsRequest struct {
	MovieID  int     `pathParam:"style=simple,explode=false,name=movie_id"`
	Language *string `default:"en-US" queryParam:"style=form,explode=true,name=language"`
	Page     *int    `default:"1" queryParam:"style=form,explode=true,name=page"`
}

func (m MovieListsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MovieListsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MovieListsRequest) GetMovieID() int {
	if o == nil {
		return 0
	}
	return o.MovieID
}

func (o *MovieListsRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *MovieListsRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

type MovieLists200ApplicationJSONResults struct {
	Description   *string     `json:"description,omitempty"`
	FavoriteCount *int64      `default:"0" json:"favorite_count"`
	ID            *int64      `default:"0" json:"id"`
	Iso6391       *string     `json:"iso_639_1,omitempty"`
	ItemCount     *int64      `default:"0" json:"item_count"`
	ListType      *string     `json:"list_type,omitempty"`
	Name          *string     `json:"name,omitempty"`
	PosterPath    interface{} `json:"poster_path,omitempty"`
}

func (m MovieLists200ApplicationJSONResults) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MovieLists200ApplicationJSONResults) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MovieLists200ApplicationJSONResults) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *MovieLists200ApplicationJSONResults) GetFavoriteCount() *int64 {
	if o == nil {
		return nil
	}
	return o.FavoriteCount
}

func (o *MovieLists200ApplicationJSONResults) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *MovieLists200ApplicationJSONResults) GetIso6391() *string {
	if o == nil {
		return nil
	}
	return o.Iso6391
}

func (o *MovieLists200ApplicationJSONResults) GetItemCount() *int64 {
	if o == nil {
		return nil
	}
	return o.ItemCount
}

func (o *MovieLists200ApplicationJSONResults) GetListType() *string {
	if o == nil {
		return nil
	}
	return o.ListType
}

func (o *MovieLists200ApplicationJSONResults) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *MovieLists200ApplicationJSONResults) GetPosterPath() interface{} {
	if o == nil {
		return nil
	}
	return o.PosterPath
}

// MovieLists200ApplicationJSON - 200
type MovieLists200ApplicationJSON struct {
	ID           *int64                                `default:"0" json:"id"`
	Page         *int64                                `default:"0" json:"page"`
	Results      []MovieLists200ApplicationJSONResults `json:"results,omitempty"`
	TotalPages   *int64                                `default:"0" json:"total_pages"`
	TotalResults *int64                                `default:"0" json:"total_results"`
}

func (m MovieLists200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MovieLists200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MovieLists200ApplicationJSON) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *MovieLists200ApplicationJSON) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *MovieLists200ApplicationJSON) GetResults() []MovieLists200ApplicationJSONResults {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *MovieLists200ApplicationJSON) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

func (o *MovieLists200ApplicationJSON) GetTotalResults() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalResults
}

type MovieListsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	MovieLists200ApplicationJSONObject *MovieLists200ApplicationJSON
}

func (o *MovieListsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MovieListsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MovieListsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MovieListsResponse) GetMovieLists200ApplicationJSONObject() *MovieLists200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.MovieLists200ApplicationJSONObject
}
