// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type SearchPersonRequest struct {
	Query        string  `queryParam:"style=form,explode=true,name=query"`
	IncludeAdult *bool   `default:"false" queryParam:"style=form,explode=true,name=include_adult"`
	Language     *string `default:"en-US" queryParam:"style=form,explode=true,name=language"`
	Page         *int    `default:"1" queryParam:"style=form,explode=true,name=page"`
}

func (s SearchPersonRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchPersonRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SearchPersonRequest) GetQuery() string {
	if o == nil {
		return ""
	}
	return o.Query
}

func (o *SearchPersonRequest) GetIncludeAdult() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeAdult
}

func (o *SearchPersonRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *SearchPersonRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

type SearchPerson200ApplicationJSONResultsKnownFor struct {
	Adult            *bool    `default:"true" json:"adult"`
	BackdropPath     *string  `json:"backdrop_path,omitempty"`
	GenreIds         []int64  `json:"genre_ids,omitempty"`
	ID               *int64   `default:"0" json:"id"`
	MediaType        *string  `json:"media_type,omitempty"`
	OriginalLanguage *string  `json:"original_language,omitempty"`
	OriginalTitle    *string  `json:"original_title,omitempty"`
	Overview         *string  `json:"overview,omitempty"`
	Popularity       *float64 `default:"0" json:"popularity"`
	PosterPath       *string  `json:"poster_path,omitempty"`
	ReleaseDate      *string  `json:"release_date,omitempty"`
	Title            *string  `json:"title,omitempty"`
	Video            *bool    `default:"true" json:"video"`
	VoteAverage      *float64 `default:"0" json:"vote_average"`
	VoteCount        *int64   `default:"0" json:"vote_count"`
}

func (s SearchPerson200ApplicationJSONResultsKnownFor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchPerson200ApplicationJSONResultsKnownFor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetBackdropPath() *string {
	if o == nil {
		return nil
	}
	return o.BackdropPath
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetGenreIds() []int64 {
	if o == nil {
		return nil
	}
	return o.GenreIds
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetMediaType() *string {
	if o == nil {
		return nil
	}
	return o.MediaType
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetOriginalLanguage() *string {
	if o == nil {
		return nil
	}
	return o.OriginalLanguage
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetOriginalTitle() *string {
	if o == nil {
		return nil
	}
	return o.OriginalTitle
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetOverview() *string {
	if o == nil {
		return nil
	}
	return o.Overview
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetPosterPath() *string {
	if o == nil {
		return nil
	}
	return o.PosterPath
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetReleaseDate() *string {
	if o == nil {
		return nil
	}
	return o.ReleaseDate
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetVideo() *bool {
	if o == nil {
		return nil
	}
	return o.Video
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetVoteAverage() *float64 {
	if o == nil {
		return nil
	}
	return o.VoteAverage
}

func (o *SearchPerson200ApplicationJSONResultsKnownFor) GetVoteCount() *int64 {
	if o == nil {
		return nil
	}
	return o.VoteCount
}

type SearchPerson200ApplicationJSONResults struct {
	Adult              *bool                                           `default:"true" json:"adult"`
	Gender             *int64                                          `default:"0" json:"gender"`
	ID                 *int64                                          `default:"0" json:"id"`
	KnownFor           []SearchPerson200ApplicationJSONResultsKnownFor `json:"known_for,omitempty"`
	KnownForDepartment *string                                         `json:"known_for_department,omitempty"`
	Name               *string                                         `json:"name,omitempty"`
	OriginalName       *string                                         `json:"original_name,omitempty"`
	Popularity         *float64                                        `default:"0" json:"popularity"`
	ProfilePath        *string                                         `json:"profile_path,omitempty"`
}

func (s SearchPerson200ApplicationJSONResults) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchPerson200ApplicationJSONResults) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SearchPerson200ApplicationJSONResults) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *SearchPerson200ApplicationJSONResults) GetGender() *int64 {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *SearchPerson200ApplicationJSONResults) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *SearchPerson200ApplicationJSONResults) GetKnownFor() []SearchPerson200ApplicationJSONResultsKnownFor {
	if o == nil {
		return nil
	}
	return o.KnownFor
}

func (o *SearchPerson200ApplicationJSONResults) GetKnownForDepartment() *string {
	if o == nil {
		return nil
	}
	return o.KnownForDepartment
}

func (o *SearchPerson200ApplicationJSONResults) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *SearchPerson200ApplicationJSONResults) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *SearchPerson200ApplicationJSONResults) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *SearchPerson200ApplicationJSONResults) GetProfilePath() *string {
	if o == nil {
		return nil
	}
	return o.ProfilePath
}

// SearchPerson200ApplicationJSON - 200
type SearchPerson200ApplicationJSON struct {
	Page         *int64                                  `default:"0" json:"page"`
	Results      []SearchPerson200ApplicationJSONResults `json:"results,omitempty"`
	TotalPages   *int64                                  `default:"0" json:"total_pages"`
	TotalResults *int64                                  `default:"0" json:"total_results"`
}

func (s SearchPerson200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchPerson200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SearchPerson200ApplicationJSON) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *SearchPerson200ApplicationJSON) GetResults() []SearchPerson200ApplicationJSONResults {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *SearchPerson200ApplicationJSON) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

func (o *SearchPerson200ApplicationJSON) GetTotalResults() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalResults
}

type SearchPersonResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	SearchPerson200ApplicationJSONObject *SearchPerson200ApplicationJSON
}

func (o *SearchPersonResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SearchPersonResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SearchPersonResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *SearchPersonResponse) GetSearchPerson200ApplicationJSONObject() *SearchPerson200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.SearchPerson200ApplicationJSONObject
}
