// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type TvEpisodeCreditsRequest struct {
	EpisodeNumber int     `pathParam:"style=simple,explode=false,name=episode_number"`
	SeasonNumber  int     `pathParam:"style=simple,explode=false,name=season_number"`
	SeriesID      int     `pathParam:"style=simple,explode=false,name=series_id"`
	Language      *string `default:"en-US" queryParam:"style=form,explode=true,name=language"`
}

func (t TvEpisodeCreditsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvEpisodeCreditsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvEpisodeCreditsRequest) GetEpisodeNumber() int {
	if o == nil {
		return 0
	}
	return o.EpisodeNumber
}

func (o *TvEpisodeCreditsRequest) GetSeasonNumber() int {
	if o == nil {
		return 0
	}
	return o.SeasonNumber
}

func (o *TvEpisodeCreditsRequest) GetSeriesID() int {
	if o == nil {
		return 0
	}
	return o.SeriesID
}

func (o *TvEpisodeCreditsRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

type TvEpisodeCredits200ApplicationJSONCast struct {
	Adult              *bool    `default:"true" json:"adult"`
	Character          *string  `json:"character,omitempty"`
	CreditID           *string  `json:"credit_id,omitempty"`
	Gender             *int64   `default:"0" json:"gender"`
	ID                 *int64   `default:"0" json:"id"`
	KnownForDepartment *string  `json:"known_for_department,omitempty"`
	Name               *string  `json:"name,omitempty"`
	Order              *int64   `default:"0" json:"order"`
	OriginalName       *string  `json:"original_name,omitempty"`
	Popularity         *float64 `default:"0" json:"popularity"`
	ProfilePath        *string  `json:"profile_path,omitempty"`
}

func (t TvEpisodeCredits200ApplicationJSONCast) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvEpisodeCredits200ApplicationJSONCast) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvEpisodeCredits200ApplicationJSONCast) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *TvEpisodeCredits200ApplicationJSONCast) GetCharacter() *string {
	if o == nil {
		return nil
	}
	return o.Character
}

func (o *TvEpisodeCredits200ApplicationJSONCast) GetCreditID() *string {
	if o == nil {
		return nil
	}
	return o.CreditID
}

func (o *TvEpisodeCredits200ApplicationJSONCast) GetGender() *int64 {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *TvEpisodeCredits200ApplicationJSONCast) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TvEpisodeCredits200ApplicationJSONCast) GetKnownForDepartment() *string {
	if o == nil {
		return nil
	}
	return o.KnownForDepartment
}

func (o *TvEpisodeCredits200ApplicationJSONCast) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TvEpisodeCredits200ApplicationJSONCast) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *TvEpisodeCredits200ApplicationJSONCast) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *TvEpisodeCredits200ApplicationJSONCast) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *TvEpisodeCredits200ApplicationJSONCast) GetProfilePath() *string {
	if o == nil {
		return nil
	}
	return o.ProfilePath
}

type TvEpisodeCredits200ApplicationJSONCrew struct {
	Adult              *bool    `default:"true" json:"adult"`
	CreditID           *string  `json:"credit_id,omitempty"`
	Department         *string  `json:"department,omitempty"`
	Gender             *int64   `default:"0" json:"gender"`
	ID                 *int64   `default:"0" json:"id"`
	Job                *string  `json:"job,omitempty"`
	KnownForDepartment *string  `json:"known_for_department,omitempty"`
	Name               *string  `json:"name,omitempty"`
	OriginalName       *string  `json:"original_name,omitempty"`
	Popularity         *float64 `default:"0" json:"popularity"`
	ProfilePath        *string  `json:"profile_path,omitempty"`
}

func (t TvEpisodeCredits200ApplicationJSONCrew) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvEpisodeCredits200ApplicationJSONCrew) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvEpisodeCredits200ApplicationJSONCrew) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *TvEpisodeCredits200ApplicationJSONCrew) GetCreditID() *string {
	if o == nil {
		return nil
	}
	return o.CreditID
}

func (o *TvEpisodeCredits200ApplicationJSONCrew) GetDepartment() *string {
	if o == nil {
		return nil
	}
	return o.Department
}

func (o *TvEpisodeCredits200ApplicationJSONCrew) GetGender() *int64 {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *TvEpisodeCredits200ApplicationJSONCrew) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TvEpisodeCredits200ApplicationJSONCrew) GetJob() *string {
	if o == nil {
		return nil
	}
	return o.Job
}

func (o *TvEpisodeCredits200ApplicationJSONCrew) GetKnownForDepartment() *string {
	if o == nil {
		return nil
	}
	return o.KnownForDepartment
}

func (o *TvEpisodeCredits200ApplicationJSONCrew) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TvEpisodeCredits200ApplicationJSONCrew) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *TvEpisodeCredits200ApplicationJSONCrew) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *TvEpisodeCredits200ApplicationJSONCrew) GetProfilePath() *string {
	if o == nil {
		return nil
	}
	return o.ProfilePath
}

type TvEpisodeCredits200ApplicationJSONGuestStars struct {
	Adult              *bool    `default:"true" json:"adult"`
	Character          *string  `json:"character,omitempty"`
	CreditID           *string  `json:"credit_id,omitempty"`
	Gender             *int64   `default:"0" json:"gender"`
	ID                 *int64   `default:"0" json:"id"`
	KnownForDepartment *string  `json:"known_for_department,omitempty"`
	Name               *string  `json:"name,omitempty"`
	Order              *int64   `default:"0" json:"order"`
	OriginalName       *string  `json:"original_name,omitempty"`
	Popularity         *float64 `default:"0" json:"popularity"`
	ProfilePath        *string  `json:"profile_path,omitempty"`
}

func (t TvEpisodeCredits200ApplicationJSONGuestStars) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvEpisodeCredits200ApplicationJSONGuestStars) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvEpisodeCredits200ApplicationJSONGuestStars) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *TvEpisodeCredits200ApplicationJSONGuestStars) GetCharacter() *string {
	if o == nil {
		return nil
	}
	return o.Character
}

func (o *TvEpisodeCredits200ApplicationJSONGuestStars) GetCreditID() *string {
	if o == nil {
		return nil
	}
	return o.CreditID
}

func (o *TvEpisodeCredits200ApplicationJSONGuestStars) GetGender() *int64 {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *TvEpisodeCredits200ApplicationJSONGuestStars) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TvEpisodeCredits200ApplicationJSONGuestStars) GetKnownForDepartment() *string {
	if o == nil {
		return nil
	}
	return o.KnownForDepartment
}

func (o *TvEpisodeCredits200ApplicationJSONGuestStars) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TvEpisodeCredits200ApplicationJSONGuestStars) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *TvEpisodeCredits200ApplicationJSONGuestStars) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *TvEpisodeCredits200ApplicationJSONGuestStars) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *TvEpisodeCredits200ApplicationJSONGuestStars) GetProfilePath() *string {
	if o == nil {
		return nil
	}
	return o.ProfilePath
}

// TvEpisodeCredits200ApplicationJSON - 200
type TvEpisodeCredits200ApplicationJSON struct {
	Cast       []TvEpisodeCredits200ApplicationJSONCast       `json:"cast,omitempty"`
	Crew       []TvEpisodeCredits200ApplicationJSONCrew       `json:"crew,omitempty"`
	GuestStars []TvEpisodeCredits200ApplicationJSONGuestStars `json:"guest_stars,omitempty"`
	ID         *int64                                         `default:"0" json:"id"`
}

func (t TvEpisodeCredits200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvEpisodeCredits200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvEpisodeCredits200ApplicationJSON) GetCast() []TvEpisodeCredits200ApplicationJSONCast {
	if o == nil {
		return nil
	}
	return o.Cast
}

func (o *TvEpisodeCredits200ApplicationJSON) GetCrew() []TvEpisodeCredits200ApplicationJSONCrew {
	if o == nil {
		return nil
	}
	return o.Crew
}

func (o *TvEpisodeCredits200ApplicationJSON) GetGuestStars() []TvEpisodeCredits200ApplicationJSONGuestStars {
	if o == nil {
		return nil
	}
	return o.GuestStars
}

func (o *TvEpisodeCredits200ApplicationJSON) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

type TvEpisodeCreditsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	TvEpisodeCredits200ApplicationJSONObject *TvEpisodeCredits200ApplicationJSON
}

func (o *TvEpisodeCreditsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TvEpisodeCreditsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TvEpisodeCreditsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TvEpisodeCreditsResponse) GetTvEpisodeCredits200ApplicationJSONObject() *TvEpisodeCredits200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.TvEpisodeCredits200ApplicationJSONObject
}
