// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type TvSeasonDetailsRequest struct {
	SeasonNumber int `pathParam:"style=simple,explode=false,name=season_number"`
	SeriesID     int `pathParam:"style=simple,explode=false,name=series_id"`
	// comma separated list of endpoints within this namespace, 20 items max
	AppendToResponse *string `queryParam:"style=form,explode=true,name=append_to_response"`
	Language         *string `default:"en-US" queryParam:"style=form,explode=true,name=language"`
}

func (t TvSeasonDetailsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvSeasonDetailsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvSeasonDetailsRequest) GetSeasonNumber() int {
	if o == nil {
		return 0
	}
	return o.SeasonNumber
}

func (o *TvSeasonDetailsRequest) GetSeriesID() int {
	if o == nil {
		return 0
	}
	return o.SeriesID
}

func (o *TvSeasonDetailsRequest) GetAppendToResponse() *string {
	if o == nil {
		return nil
	}
	return o.AppendToResponse
}

func (o *TvSeasonDetailsRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

type TvSeasonDetails200ApplicationJSONEpisodesCrew struct {
	Adult              *bool    `default:"true" json:"adult"`
	CreditID           *string  `json:"credit_id,omitempty"`
	Department         *string  `json:"department,omitempty"`
	Gender             *int64   `default:"0" json:"gender"`
	ID                 *int64   `default:"0" json:"id"`
	Job                *string  `json:"job,omitempty"`
	KnownForDepartment *string  `json:"known_for_department,omitempty"`
	Name               *string  `json:"name,omitempty"`
	OriginalName       *string  `json:"original_name,omitempty"`
	Popularity         *float64 `default:"0" json:"popularity"`
	ProfilePath        *string  `json:"profile_path,omitempty"`
}

func (t TvSeasonDetails200ApplicationJSONEpisodesCrew) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvSeasonDetails200ApplicationJSONEpisodesCrew) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesCrew) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesCrew) GetCreditID() *string {
	if o == nil {
		return nil
	}
	return o.CreditID
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesCrew) GetDepartment() *string {
	if o == nil {
		return nil
	}
	return o.Department
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesCrew) GetGender() *int64 {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesCrew) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesCrew) GetJob() *string {
	if o == nil {
		return nil
	}
	return o.Job
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesCrew) GetKnownForDepartment() *string {
	if o == nil {
		return nil
	}
	return o.KnownForDepartment
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesCrew) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesCrew) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesCrew) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesCrew) GetProfilePath() *string {
	if o == nil {
		return nil
	}
	return o.ProfilePath
}

type TvSeasonDetails200ApplicationJSONEpisodesGuestStars struct {
	Adult              *bool    `default:"true" json:"adult"`
	Character          *string  `json:"character,omitempty"`
	CreditID           *string  `json:"credit_id,omitempty"`
	Gender             *int64   `default:"0" json:"gender"`
	ID                 *int64   `default:"0" json:"id"`
	KnownForDepartment *string  `json:"known_for_department,omitempty"`
	Name               *string  `json:"name,omitempty"`
	Order              *int64   `default:"0" json:"order"`
	OriginalName       *string  `json:"original_name,omitempty"`
	Popularity         *float64 `default:"0" json:"popularity"`
	ProfilePath        *string  `json:"profile_path,omitempty"`
}

func (t TvSeasonDetails200ApplicationJSONEpisodesGuestStars) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) GetCharacter() *string {
	if o == nil {
		return nil
	}
	return o.Character
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) GetCreditID() *string {
	if o == nil {
		return nil
	}
	return o.CreditID
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) GetGender() *int64 {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) GetKnownForDepartment() *string {
	if o == nil {
		return nil
	}
	return o.KnownForDepartment
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *TvSeasonDetails200ApplicationJSONEpisodesGuestStars) GetProfilePath() *string {
	if o == nil {
		return nil
	}
	return o.ProfilePath
}

type TvSeasonDetails200ApplicationJSONEpisodes struct {
	AirDate        *string                                               `json:"air_date,omitempty"`
	Crew           []TvSeasonDetails200ApplicationJSONEpisodesCrew       `json:"crew,omitempty"`
	EpisodeNumber  *int64                                                `default:"0" json:"episode_number"`
	GuestStars     []TvSeasonDetails200ApplicationJSONEpisodesGuestStars `json:"guest_stars,omitempty"`
	ID             *int64                                                `default:"0" json:"id"`
	Name           *string                                               `json:"name,omitempty"`
	Overview       *string                                               `json:"overview,omitempty"`
	ProductionCode *string                                               `json:"production_code,omitempty"`
	Runtime        *int64                                                `default:"0" json:"runtime"`
	SeasonNumber   *int64                                                `default:"0" json:"season_number"`
	ShowID         *int64                                                `default:"0" json:"show_id"`
	StillPath      *string                                               `json:"still_path,omitempty"`
	VoteAverage    *float64                                              `default:"0" json:"vote_average"`
	VoteCount      *int64                                                `default:"0" json:"vote_count"`
}

func (t TvSeasonDetails200ApplicationJSONEpisodes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvSeasonDetails200ApplicationJSONEpisodes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetAirDate() *string {
	if o == nil {
		return nil
	}
	return o.AirDate
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetCrew() []TvSeasonDetails200ApplicationJSONEpisodesCrew {
	if o == nil {
		return nil
	}
	return o.Crew
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetEpisodeNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.EpisodeNumber
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetGuestStars() []TvSeasonDetails200ApplicationJSONEpisodesGuestStars {
	if o == nil {
		return nil
	}
	return o.GuestStars
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetOverview() *string {
	if o == nil {
		return nil
	}
	return o.Overview
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetProductionCode() *string {
	if o == nil {
		return nil
	}
	return o.ProductionCode
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetRuntime() *int64 {
	if o == nil {
		return nil
	}
	return o.Runtime
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetSeasonNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.SeasonNumber
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetShowID() *int64 {
	if o == nil {
		return nil
	}
	return o.ShowID
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetStillPath() *string {
	if o == nil {
		return nil
	}
	return o.StillPath
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetVoteAverage() *float64 {
	if o == nil {
		return nil
	}
	return o.VoteAverage
}

func (o *TvSeasonDetails200ApplicationJSONEpisodes) GetVoteCount() *int64 {
	if o == nil {
		return nil
	}
	return o.VoteCount
}

// TvSeasonDetails200ApplicationJSON - 200
type TvSeasonDetails200ApplicationJSON struct {
	InternalID   *string                                     `json:"_internal_id,omitempty"`
	AirDate      *string                                     `json:"air_date,omitempty"`
	Episodes     []TvSeasonDetails200ApplicationJSONEpisodes `json:"episodes,omitempty"`
	ID           *int64                                      `default:"0" json:"id"`
	Name         *string                                     `json:"name,omitempty"`
	Overview     *string                                     `json:"overview,omitempty"`
	PosterPath   *string                                     `json:"poster_path,omitempty"`
	SeasonNumber *int64                                      `default:"0" json:"season_number"`
	VoteAverage  *float64                                    `default:"0" json:"vote_average"`
}

func (t TvSeasonDetails200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvSeasonDetails200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvSeasonDetails200ApplicationJSON) GetInternalID() *string {
	if o == nil {
		return nil
	}
	return o.InternalID
}

func (o *TvSeasonDetails200ApplicationJSON) GetAirDate() *string {
	if o == nil {
		return nil
	}
	return o.AirDate
}

func (o *TvSeasonDetails200ApplicationJSON) GetEpisodes() []TvSeasonDetails200ApplicationJSONEpisodes {
	if o == nil {
		return nil
	}
	return o.Episodes
}

func (o *TvSeasonDetails200ApplicationJSON) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TvSeasonDetails200ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TvSeasonDetails200ApplicationJSON) GetOverview() *string {
	if o == nil {
		return nil
	}
	return o.Overview
}

func (o *TvSeasonDetails200ApplicationJSON) GetPosterPath() *string {
	if o == nil {
		return nil
	}
	return o.PosterPath
}

func (o *TvSeasonDetails200ApplicationJSON) GetSeasonNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.SeasonNumber
}

func (o *TvSeasonDetails200ApplicationJSON) GetVoteAverage() *float64 {
	if o == nil {
		return nil
	}
	return o.VoteAverage
}

type TvSeasonDetailsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	TvSeasonDetails200ApplicationJSONObject *TvSeasonDetails200ApplicationJSON
}

func (o *TvSeasonDetailsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TvSeasonDetailsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TvSeasonDetailsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TvSeasonDetailsResponse) GetTvSeasonDetails200ApplicationJSONObject() *TvSeasonDetails200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.TvSeasonDetails200ApplicationJSONObject
}
