// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type TvSeriesScreenedTheatricallyRequest struct {
	SeriesID int `pathParam:"style=simple,explode=false,name=series_id"`
}

func (o *TvSeriesScreenedTheatricallyRequest) GetSeriesID() int {
	if o == nil {
		return 0
	}
	return o.SeriesID
}

type TvSeriesScreenedTheatrically200ApplicationJSONResults struct {
	EpisodeNumber *int64 `default:"0" json:"episode_number"`
	ID            *int64 `default:"0" json:"id"`
	SeasonNumber  *int64 `default:"0" json:"season_number"`
}

func (t TvSeriesScreenedTheatrically200ApplicationJSONResults) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvSeriesScreenedTheatrically200ApplicationJSONResults) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvSeriesScreenedTheatrically200ApplicationJSONResults) GetEpisodeNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.EpisodeNumber
}

func (o *TvSeriesScreenedTheatrically200ApplicationJSONResults) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TvSeriesScreenedTheatrically200ApplicationJSONResults) GetSeasonNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.SeasonNumber
}

// TvSeriesScreenedTheatrically200ApplicationJSON - 200
type TvSeriesScreenedTheatrically200ApplicationJSON struct {
	ID      *int64                                                  `default:"0" json:"id"`
	Results []TvSeriesScreenedTheatrically200ApplicationJSONResults `json:"results,omitempty"`
}

func (t TvSeriesScreenedTheatrically200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvSeriesScreenedTheatrically200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvSeriesScreenedTheatrically200ApplicationJSON) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TvSeriesScreenedTheatrically200ApplicationJSON) GetResults() []TvSeriesScreenedTheatrically200ApplicationJSONResults {
	if o == nil {
		return nil
	}
	return o.Results
}

type TvSeriesScreenedTheatricallyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	TvSeriesScreenedTheatrically200ApplicationJSONObject *TvSeriesScreenedTheatrically200ApplicationJSON
}

func (o *TvSeriesScreenedTheatricallyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TvSeriesScreenedTheatricallyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TvSeriesScreenedTheatricallyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TvSeriesScreenedTheatricallyResponse) GetTvSeriesScreenedTheatrically200ApplicationJSONObject() *TvSeriesScreenedTheatrically200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.TvSeriesScreenedTheatrically200ApplicationJSONObject
}
