// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type TvSeasonCreditsRequest struct {
	SeasonNumber int     `pathParam:"style=simple,explode=false,name=season_number"`
	SeriesID     int     `pathParam:"style=simple,explode=false,name=series_id"`
	Language     *string `default:"en-US" queryParam:"style=form,explode=true,name=language"`
}

func (t TvSeasonCreditsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvSeasonCreditsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvSeasonCreditsRequest) GetSeasonNumber() int {
	if o == nil {
		return 0
	}
	return o.SeasonNumber
}

func (o *TvSeasonCreditsRequest) GetSeriesID() int {
	if o == nil {
		return 0
	}
	return o.SeriesID
}

func (o *TvSeasonCreditsRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

type TvSeasonCredits200ApplicationJSONCast struct {
	Adult              *bool    `default:"true" json:"adult"`
	Character          *string  `json:"character,omitempty"`
	CreditID           *string  `json:"credit_id,omitempty"`
	Gender             *int64   `default:"0" json:"gender"`
	ID                 *int64   `default:"0" json:"id"`
	KnownForDepartment *string  `json:"known_for_department,omitempty"`
	Name               *string  `json:"name,omitempty"`
	Order              *int64   `default:"0" json:"order"`
	OriginalName       *string  `json:"original_name,omitempty"`
	Popularity         *float64 `default:"0" json:"popularity"`
	ProfilePath        *string  `json:"profile_path,omitempty"`
}

func (t TvSeasonCredits200ApplicationJSONCast) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvSeasonCredits200ApplicationJSONCast) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvSeasonCredits200ApplicationJSONCast) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *TvSeasonCredits200ApplicationJSONCast) GetCharacter() *string {
	if o == nil {
		return nil
	}
	return o.Character
}

func (o *TvSeasonCredits200ApplicationJSONCast) GetCreditID() *string {
	if o == nil {
		return nil
	}
	return o.CreditID
}

func (o *TvSeasonCredits200ApplicationJSONCast) GetGender() *int64 {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *TvSeasonCredits200ApplicationJSONCast) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TvSeasonCredits200ApplicationJSONCast) GetKnownForDepartment() *string {
	if o == nil {
		return nil
	}
	return o.KnownForDepartment
}

func (o *TvSeasonCredits200ApplicationJSONCast) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TvSeasonCredits200ApplicationJSONCast) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *TvSeasonCredits200ApplicationJSONCast) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *TvSeasonCredits200ApplicationJSONCast) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *TvSeasonCredits200ApplicationJSONCast) GetProfilePath() *string {
	if o == nil {
		return nil
	}
	return o.ProfilePath
}

type TvSeasonCredits200ApplicationJSONCrew struct {
	Adult              *bool       `default:"true" json:"adult"`
	CreditID           *string     `json:"credit_id,omitempty"`
	Department         *string     `json:"department,omitempty"`
	Gender             *int64      `default:"0" json:"gender"`
	ID                 *int64      `default:"0" json:"id"`
	Job                *string     `json:"job,omitempty"`
	KnownForDepartment *string     `json:"known_for_department,omitempty"`
	Name               *string     `json:"name,omitempty"`
	OriginalName       *string     `json:"original_name,omitempty"`
	Popularity         *float64    `default:"0" json:"popularity"`
	ProfilePath        interface{} `json:"profile_path,omitempty"`
}

func (t TvSeasonCredits200ApplicationJSONCrew) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvSeasonCredits200ApplicationJSONCrew) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvSeasonCredits200ApplicationJSONCrew) GetAdult() *bool {
	if o == nil {
		return nil
	}
	return o.Adult
}

func (o *TvSeasonCredits200ApplicationJSONCrew) GetCreditID() *string {
	if o == nil {
		return nil
	}
	return o.CreditID
}

func (o *TvSeasonCredits200ApplicationJSONCrew) GetDepartment() *string {
	if o == nil {
		return nil
	}
	return o.Department
}

func (o *TvSeasonCredits200ApplicationJSONCrew) GetGender() *int64 {
	if o == nil {
		return nil
	}
	return o.Gender
}

func (o *TvSeasonCredits200ApplicationJSONCrew) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TvSeasonCredits200ApplicationJSONCrew) GetJob() *string {
	if o == nil {
		return nil
	}
	return o.Job
}

func (o *TvSeasonCredits200ApplicationJSONCrew) GetKnownForDepartment() *string {
	if o == nil {
		return nil
	}
	return o.KnownForDepartment
}

func (o *TvSeasonCredits200ApplicationJSONCrew) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TvSeasonCredits200ApplicationJSONCrew) GetOriginalName() *string {
	if o == nil {
		return nil
	}
	return o.OriginalName
}

func (o *TvSeasonCredits200ApplicationJSONCrew) GetPopularity() *float64 {
	if o == nil {
		return nil
	}
	return o.Popularity
}

func (o *TvSeasonCredits200ApplicationJSONCrew) GetProfilePath() interface{} {
	if o == nil {
		return nil
	}
	return o.ProfilePath
}

// TvSeasonCredits200ApplicationJSON - 200
type TvSeasonCredits200ApplicationJSON struct {
	Cast []TvSeasonCredits200ApplicationJSONCast `json:"cast,omitempty"`
	Crew []TvSeasonCredits200ApplicationJSONCrew `json:"crew,omitempty"`
	ID   *int64                                  `default:"0" json:"id"`
}

func (t TvSeasonCredits200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TvSeasonCredits200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TvSeasonCredits200ApplicationJSON) GetCast() []TvSeasonCredits200ApplicationJSONCast {
	if o == nil {
		return nil
	}
	return o.Cast
}

func (o *TvSeasonCredits200ApplicationJSON) GetCrew() []TvSeasonCredits200ApplicationJSONCrew {
	if o == nil {
		return nil
	}
	return o.Crew
}

func (o *TvSeasonCredits200ApplicationJSON) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

type TvSeasonCreditsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	TvSeasonCredits200ApplicationJSONObject *TvSeasonCredits200ApplicationJSON
}

func (o *TvSeasonCreditsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TvSeasonCreditsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TvSeasonCreditsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TvSeasonCreditsResponse) GetTvSeasonCredits200ApplicationJSONObject() *TvSeasonCredits200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.TvSeasonCredits200ApplicationJSONObject
}
