// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tmdb/openapi/utils"
	"net/http"
)

type WatchProvidersMovieListRequest struct {
	Language    *string `default:"en-US" queryParam:"style=form,explode=true,name=language"`
	WatchRegion *string `queryParam:"style=form,explode=true,name=watch_region"`
}

func (w WatchProvidersMovieListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WatchProvidersMovieListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WatchProvidersMovieListRequest) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *WatchProvidersMovieListRequest) GetWatchRegion() *string {
	if o == nil {
		return nil
	}
	return o.WatchRegion
}

type WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities struct {
	Ae *int64 `default:"0" json:"AE"`
	Ar *int64 `default:"0" json:"AR"`
	At *int64 `default:"0" json:"AT"`
	Au *int64 `default:"0" json:"AU"`
	Be *int64 `default:"0" json:"BE"`
	Bg *int64 `default:"0" json:"BG"`
	Bo *int64 `default:"0" json:"BO"`
	Br *int64 `default:"0" json:"BR"`
	Ca *int64 `default:"0" json:"CA"`
	Ch *int64 `default:"0" json:"CH"`
	Cl *int64 `default:"0" json:"CL"`
	Co *int64 `default:"0" json:"CO"`
	Cr *int64 `default:"0" json:"CR"`
	Cv *int64 `default:"0" json:"CV"`
	Cz *int64 `default:"0" json:"CZ"`
	De *int64 `default:"0" json:"DE"`
	Dk *int64 `default:"0" json:"DK"`
	Ec *int64 `default:"0" json:"EC"`
	Ee *int64 `default:"0" json:"EE"`
	Eg *int64 `default:"0" json:"EG"`
	Es *int64 `default:"0" json:"ES"`
	Fi *int64 `default:"0" json:"FI"`
	Fr *int64 `default:"0" json:"FR"`
	Gb *int64 `default:"0" json:"GB"`
	Gh *int64 `default:"0" json:"GH"`
	Gr *int64 `default:"0" json:"GR"`
	Gt *int64 `default:"0" json:"GT"`
	Hk *int64 `default:"0" json:"HK"`
	Hn *int64 `default:"0" json:"HN"`
	Hu *int64 `default:"0" json:"HU"`
	ID *int64 `default:"0" json:"ID"`
	Ie *int64 `default:"0" json:"IE"`
	Il *int64 `default:"0" json:"IL"`
	In *int64 `default:"0" json:"IN"`
	It *int64 `default:"0" json:"IT"`
	Jp *int64 `default:"0" json:"JP"`
	Lt *int64 `default:"0" json:"LT"`
	Lv *int64 `default:"0" json:"LV"`
	Mu *int64 `default:"0" json:"MU"`
	Mx *int64 `default:"0" json:"MX"`
	My *int64 `default:"0" json:"MY"`
	Mz *int64 `default:"0" json:"MZ"`
	Nl *int64 `default:"0" json:"NL"`
	No *int64 `default:"0" json:"NO"`
	Nz *int64 `default:"0" json:"NZ"`
	Pe *int64 `default:"0" json:"PE"`
	Ph *int64 `default:"0" json:"PH"`
	Pl *int64 `default:"0" json:"PL"`
	Pt *int64 `default:"0" json:"PT"`
	Py *int64 `default:"0" json:"PY"`
	Ru *int64 `default:"0" json:"RU"`
	Sa *int64 `default:"0" json:"SA"`
	Se *int64 `default:"0" json:"SE"`
	Sg *int64 `default:"0" json:"SG"`
	Si *int64 `default:"0" json:"SI"`
	Sk *int64 `default:"0" json:"SK"`
	Th *int64 `default:"0" json:"TH"`
	Tr *int64 `default:"0" json:"TR"`
	Tw *int64 `default:"0" json:"TW"`
	Ug *int64 `default:"0" json:"UG"`
	Us *int64 `default:"0" json:"US"`
	Ve *int64 `default:"0" json:"VE"`
	Za *int64 `default:"0" json:"ZA"`
}

func (w WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetAe() *int64 {
	if o == nil {
		return nil
	}
	return o.Ae
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetAr() *int64 {
	if o == nil {
		return nil
	}
	return o.Ar
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetAt() *int64 {
	if o == nil {
		return nil
	}
	return o.At
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetAu() *int64 {
	if o == nil {
		return nil
	}
	return o.Au
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetBe() *int64 {
	if o == nil {
		return nil
	}
	return o.Be
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetBg() *int64 {
	if o == nil {
		return nil
	}
	return o.Bg
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetBo() *int64 {
	if o == nil {
		return nil
	}
	return o.Bo
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetBr() *int64 {
	if o == nil {
		return nil
	}
	return o.Br
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetCa() *int64 {
	if o == nil {
		return nil
	}
	return o.Ca
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetCh() *int64 {
	if o == nil {
		return nil
	}
	return o.Ch
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetCl() *int64 {
	if o == nil {
		return nil
	}
	return o.Cl
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetCo() *int64 {
	if o == nil {
		return nil
	}
	return o.Co
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetCr() *int64 {
	if o == nil {
		return nil
	}
	return o.Cr
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetCv() *int64 {
	if o == nil {
		return nil
	}
	return o.Cv
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetCz() *int64 {
	if o == nil {
		return nil
	}
	return o.Cz
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetDe() *int64 {
	if o == nil {
		return nil
	}
	return o.De
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetDk() *int64 {
	if o == nil {
		return nil
	}
	return o.Dk
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetEc() *int64 {
	if o == nil {
		return nil
	}
	return o.Ec
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetEe() *int64 {
	if o == nil {
		return nil
	}
	return o.Ee
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetEg() *int64 {
	if o == nil {
		return nil
	}
	return o.Eg
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetEs() *int64 {
	if o == nil {
		return nil
	}
	return o.Es
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetFi() *int64 {
	if o == nil {
		return nil
	}
	return o.Fi
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetFr() *int64 {
	if o == nil {
		return nil
	}
	return o.Fr
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetGb() *int64 {
	if o == nil {
		return nil
	}
	return o.Gb
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetGh() *int64 {
	if o == nil {
		return nil
	}
	return o.Gh
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetGr() *int64 {
	if o == nil {
		return nil
	}
	return o.Gr
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetGt() *int64 {
	if o == nil {
		return nil
	}
	return o.Gt
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetHk() *int64 {
	if o == nil {
		return nil
	}
	return o.Hk
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetHn() *int64 {
	if o == nil {
		return nil
	}
	return o.Hn
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetHu() *int64 {
	if o == nil {
		return nil
	}
	return o.Hu
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetIe() *int64 {
	if o == nil {
		return nil
	}
	return o.Ie
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetIl() *int64 {
	if o == nil {
		return nil
	}
	return o.Il
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetIn() *int64 {
	if o == nil {
		return nil
	}
	return o.In
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetIt() *int64 {
	if o == nil {
		return nil
	}
	return o.It
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetJp() *int64 {
	if o == nil {
		return nil
	}
	return o.Jp
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetLt() *int64 {
	if o == nil {
		return nil
	}
	return o.Lt
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetLv() *int64 {
	if o == nil {
		return nil
	}
	return o.Lv
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetMu() *int64 {
	if o == nil {
		return nil
	}
	return o.Mu
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetMx() *int64 {
	if o == nil {
		return nil
	}
	return o.Mx
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetMy() *int64 {
	if o == nil {
		return nil
	}
	return o.My
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetMz() *int64 {
	if o == nil {
		return nil
	}
	return o.Mz
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetNl() *int64 {
	if o == nil {
		return nil
	}
	return o.Nl
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetNo() *int64 {
	if o == nil {
		return nil
	}
	return o.No
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetNz() *int64 {
	if o == nil {
		return nil
	}
	return o.Nz
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetPe() *int64 {
	if o == nil {
		return nil
	}
	return o.Pe
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetPh() *int64 {
	if o == nil {
		return nil
	}
	return o.Ph
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetPl() *int64 {
	if o == nil {
		return nil
	}
	return o.Pl
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetPt() *int64 {
	if o == nil {
		return nil
	}
	return o.Pt
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetPy() *int64 {
	if o == nil {
		return nil
	}
	return o.Py
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetRu() *int64 {
	if o == nil {
		return nil
	}
	return o.Ru
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetSa() *int64 {
	if o == nil {
		return nil
	}
	return o.Sa
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetSe() *int64 {
	if o == nil {
		return nil
	}
	return o.Se
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetSg() *int64 {
	if o == nil {
		return nil
	}
	return o.Sg
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetSi() *int64 {
	if o == nil {
		return nil
	}
	return o.Si
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetSk() *int64 {
	if o == nil {
		return nil
	}
	return o.Sk
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetTh() *int64 {
	if o == nil {
		return nil
	}
	return o.Th
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetTr() *int64 {
	if o == nil {
		return nil
	}
	return o.Tr
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetTw() *int64 {
	if o == nil {
		return nil
	}
	return o.Tw
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetUg() *int64 {
	if o == nil {
		return nil
	}
	return o.Ug
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetUs() *int64 {
	if o == nil {
		return nil
	}
	return o.Us
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetVe() *int64 {
	if o == nil {
		return nil
	}
	return o.Ve
}

func (o *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities) GetZa() *int64 {
	if o == nil {
		return nil
	}
	return o.Za
}

type WatchProvidersMovieList200ApplicationJSONResults struct {
	DisplayPriorities *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities `json:"display_priorities,omitempty"`
	DisplayPriority   *int64                                                             `default:"0" json:"display_priority"`
	LogoPath          *string                                                            `json:"logo_path,omitempty"`
	ProviderID        *int64                                                             `default:"0" json:"provider_id"`
	ProviderName      *string                                                            `json:"provider_name,omitempty"`
}

func (w WatchProvidersMovieList200ApplicationJSONResults) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WatchProvidersMovieList200ApplicationJSONResults) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WatchProvidersMovieList200ApplicationJSONResults) GetDisplayPriorities() *WatchProvidersMovieList200ApplicationJSONResultsDisplayPriorities {
	if o == nil {
		return nil
	}
	return o.DisplayPriorities
}

func (o *WatchProvidersMovieList200ApplicationJSONResults) GetDisplayPriority() *int64 {
	if o == nil {
		return nil
	}
	return o.DisplayPriority
}

func (o *WatchProvidersMovieList200ApplicationJSONResults) GetLogoPath() *string {
	if o == nil {
		return nil
	}
	return o.LogoPath
}

func (o *WatchProvidersMovieList200ApplicationJSONResults) GetProviderID() *int64 {
	if o == nil {
		return nil
	}
	return o.ProviderID
}

func (o *WatchProvidersMovieList200ApplicationJSONResults) GetProviderName() *string {
	if o == nil {
		return nil
	}
	return o.ProviderName
}

// WatchProvidersMovieList200ApplicationJSON - 200
type WatchProvidersMovieList200ApplicationJSON struct {
	Results []WatchProvidersMovieList200ApplicationJSONResults `json:"results,omitempty"`
}

func (o *WatchProvidersMovieList200ApplicationJSON) GetResults() []WatchProvidersMovieList200ApplicationJSONResults {
	if o == nil {
		return nil
	}
	return o.Results
}

type WatchProvidersMovieListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// 200
	WatchProvidersMovieList200ApplicationJSONObject *WatchProvidersMovieList200ApplicationJSON
}

func (o *WatchProvidersMovieListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *WatchProvidersMovieListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *WatchProvidersMovieListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *WatchProvidersMovieListResponse) GetWatchProvidersMovieList200ApplicationJSONObject() *WatchProvidersMovieList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.WatchProvidersMovieList200ApplicationJSONObject
}
