// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Security struct {
	Sec0 string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *Security) GetSec0() string {
	if o == nil {
		return ""
	}
	return o.Sec0
}
